### ISSUE TITLE
Putting link on IP

### ISSUE THREAD

**Issue by szepeviktor** [fjarrett/user-session-control#11]
Could I get a filter that creates `<a link>` on the user IP`</a>`ddress?

`http://bgp.he.net/ip/%s`

**Comment by frankiejarrett** [comment]
@szepeviktor If you submit a PR I will review and merge it

**Comment by szepeviktor** [comment]
Uglyfied: https://github.com/fjarrett/user-session-control/pull/12

**Comment by szepeviktor** [comment]
Thank you.
