### ISSUE TITLE
travis.before_script.sh is missing

### ISSUE THREAD

**Issue by szepeviktor** [fjarrett/user-session-control#14]
Here https://github.com/fjarrett/user-session-control/blob/master/.travis.yml#L15
in action https://travis-ci.org/fjarrett/user-session-control/jobs/151768916

And really, there is no such file
https://github.com/xwp/wp-dev-lib/tree/3953c2b0beaf2f7bbdd1cb26d8f88aad89f722e8

**Comment by szepeviktor** [comment]
Removed here https://github.com/xwp/wp-dev-lib/pull/127/files#diff-5c32d03d78c7cb0c4d66641f434f3024

**Comment by frankiejarrett** [comment]
@szepeviktor All good now, thank you!

https://travis-ci.org/fjarrett/user-session-control/builds/152818345

**Comment by szepeviktor** [comment]
OK!
