### ISSUE TITLE
[off] Simple custom admin form 

### ISSUE THREAD

**Issue by szepeviktor** [fjarrett/user-session-control#15]
Hello @fjarrett !

I'd like to develop a simple messaging plugin. It would be a simple form to send emails to other WP users.

![sendmessage](https://cloud.githubusercontent.com/assets/952007/22185899/e41d9b10-e0ed-11e6-89c4-001f78084495.png)

Do you have a how-to or a checklist how to create a WordPress-conform admin form?
The result would not be stored at all.

Thanks.

**Comment by frankiejarrett** [comment]
Hey @szepeviktor! Nice, that is a really cool idea.

I don't have a checklist, my approach is to steal/mimic whatever UI is already used somewhere in core that looks reusable for my purposes. And if not, I look at highly-popular plugins that typically do a good job of pretending to be core-like, my shortlist would be WooCommerce, EDD or anything by @justintadlock or @jjj 😸

**Comment by szepeviktor** [comment]
Thank you for your answer. 

It is already published
https://wordpress.org/plugins/send-message/

I was copying logic from core. 

All the best! 


-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!

**Comment by JJJ** [comment]
💜
